package com.app.util;

import org.apache.ibatis.jdbc.ScriptRunner;
import org.mindrot.jbcrypt.BCrypt;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 * Applies {@code db/oracle/schema.sql} and seeds reference data once per empty database.
 */
public final class OracleBootstrap {

    private OracleBootstrap() {}

    public static void install(Connection c) throws Exception {
        boolean hasStart = coreTableExists(c, "SOUS_DIRECTIONS");
        boolean hasEnd = coreTableExists(c, "MONTHLY_REPORTS");
        if (!hasStart) {
            try (InputStream in = OracleBootstrap.class.getResourceAsStream("/db/oracle/schema.sql")) {
                if (in == null) {
                    throw new IllegalStateException("Missing classpath resource /db/oracle/schema.sql");
                }
                ScriptRunner runner = new ScriptRunner(c);
                runner.setSendFullScript(false);
                runner.setStopOnError(true);
                runner.setLogWriter(null);
                runner.setErrorLogWriter(null);
                runner.runScript(new InputStreamReader(in, StandardCharsets.UTF_8));
            }
        } else if (hasEnd) {
            System.out.println("Oracle schema already exists, skipping schema.sql bootstrap.");
        } else {
            throw new IllegalStateException(
                    "Detected partial Oracle schema bootstrap. Drop/recreate schema user (or DROP USER ... CASCADE) and rerun.");
        }
        seedCoreData(c);
        DB.seedDirectionSousDirectionMappingsOracle(c);
        DB.purgeLegacyAcronymSousDirections(c);
        ensureFieldMissionsTables(c);
        ensureFieldMissionDescriptionColumn(c);
        ensureFieldMissionOrderColumns(c);
        ensureFieldMissionOrderAttachmentsTable(c);
        ensureFieldMissionDetailAttachmentsTable(c);
        ensureFieldMissionReportAuthorColumn(c);
        ensureUserAbsencesTable(c);
        ensureUserAbsencesMissionIdColumn(c);
        ensureCourierTables(c);
        ensureCourierPacketExtraColumns(c);
        ensureCourierPacketExtraDirectionsTable(c);
        ensureMyShiftTables(c);
        ensureMyShiftPlannedTable(c);
        ensureUserOtpColumns(c);
        ensureUserAttendanceSignatureColumn(c);
    }

    private static void ensureUserOtpColumns(Connection c) throws Exception {
        String[] alters = {
                "ALTER TABLE users ADD (password_otp_hash VARCHAR2(255))",
                "ALTER TABLE users ADD (password_otp_expires_at VARCHAR2(32))"
        };
        for (String ddl : alters) {
            try (java.sql.Statement st = c.createStatement()) {
                st.execute(ddl);
            } catch (Exception e) {
                if (e.getMessage() == null
                        || (!e.getMessage().contains("ORA-01430") && !e.getMessage().contains("already exists"))) {
                    System.out.println("Oracle ensureUserOtpColumns: " + e.getMessage());
                }
            }
        }
    }

    private static void ensureUserAttendanceSignatureColumn(Connection c) throws Exception {
        try (java.sql.Statement st = c.createStatement()) {
            st.execute("ALTER TABLE users ADD (attendance_signature VARCHAR2(64))");
        } catch (Exception e) {
            if (e.getMessage() == null || !e.getMessage().contains("ORA-01430")) {
                System.out.println("Oracle ensureUserAttendanceSignatureColumn: " + e.getMessage());
            }
        }
        AttendanceSignatureUtil.backfillMissing(c);
    }

    /** Adds leave/holiday periods table when upgrading Oracle. */
    private static void ensureCourierTables(Connection c) throws Exception {
        if (coreTableExists(c, "COURIER_PACKETS")) {
            return;
        }
        String[] ddl = {
                """
                CREATE TABLE courier_packets (
                  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  ref_code VARCHAR2(64) NOT NULL,
                  title VARCHAR2(4000) NOT NULL,
                  description CLOB,
                  status VARCHAR2(32) NOT NULL,
                  target_direction_id NUMBER,
                  target_sous_direction_id NUMBER,
                  created_by NUMBER NOT NULL,
                  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                  assigned_sous_directeur_id NUMBER,
                  assigned_inspecteur_id NUMBER,
                  assigned_controleur_id NUMBER,
                  assigned_verificateur_id NUMBER,
                  resolved_at TIMESTAMP,
                  resolved_by NUMBER,
                  CONSTRAINT uq_courier_ref UNIQUE (ref_code),
                  CONSTRAINT fk_cp_created FOREIGN KEY (created_by) REFERENCES users(id),
                  CONSTRAINT fk_cp_tdir FOREIGN KEY (target_direction_id) REFERENCES directions(id),
                  CONSTRAINT fk_cp_tsous FOREIGN KEY (target_sous_direction_id) REFERENCES sous_directions(id),
                  CONSTRAINT fk_cp_sdir FOREIGN KEY (assigned_sous_directeur_id) REFERENCES users(id),
                  CONSTRAINT fk_cp_insp FOREIGN KEY (assigned_inspecteur_id) REFERENCES users(id),
                  CONSTRAINT fk_cp_ctrl FOREIGN KEY (assigned_controleur_id) REFERENCES users(id),
                  CONSTRAINT fk_cp_ver FOREIGN KEY (assigned_verificateur_id) REFERENCES users(id),
                  CONSTRAINT fk_cp_resb FOREIGN KEY (resolved_by) REFERENCES users(id)
                )
                """,
                """
                CREATE TABLE courier_journey_events (
                  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  packet_id NUMBER NOT NULL,
                  event_type VARCHAR2(64) NOT NULL,
                  at_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                  actor_user_id NUMBER,
                  related_user_id NUMBER,
                  direction_id NUMBER,
                  sous_direction_id NUMBER,
                  note CLOB,
                  CONSTRAINT fk_cje_p FOREIGN KEY (packet_id) REFERENCES courier_packets(id) ON DELETE CASCADE,
                  CONSTRAINT fk_cje_act FOREIGN KEY (actor_user_id) REFERENCES users(id),
                  CONSTRAINT fk_cje_rel FOREIGN KEY (related_user_id) REFERENCES users(id)
                )
                """,
                "CREATE INDEX idx_courier_packets_dir ON courier_packets (target_direction_id)",
                "CREATE INDEX idx_courier_packets_sd ON courier_packets (target_sous_direction_id)",
                "CREATE INDEX idx_cje_packet ON courier_journey_events (packet_id)"
        };
        try (java.sql.Statement st = c.createStatement()) {
            for (String sql : ddl) {
                st.execute(sql);
            }
        }
        System.out.println("Oracle: created courier_packets / courier_journey_events tables.");
    }

    private static void ensureCourierPacketExtraColumns(Connection c) throws Exception {
        if (!coreTableExists(c, "COURIER_PACKETS")) {
            return;
        }
        String[] alters = {
                "ALTER TABLE courier_packets ADD (sender VARCHAR2(4000))",
                "ALTER TABLE courier_packets ADD (priority VARCHAR2(32) DEFAULT 'MEDIUM')",
                "ALTER TABLE courier_packets ADD (registration_date VARCHAR2(32))",
                "ALTER TABLE courier_packets ADD (attachment_path VARCHAR2(4000))",
                "ALTER TABLE courier_packets ADD (secretaire_can_route_sous NUMBER(1) DEFAULT 0 NOT NULL)",
                "ALTER TABLE courier_packets ADD (linked_ticket_id NUMBER)"
        };
        for (String ddl : alters) {
            try (java.sql.Statement st = c.createStatement()) {
                st.execute(ddl);
            } catch (Exception e) {
                if (e.getMessage() == null
                        || (!e.getMessage().contains("ORA-01430") && !e.getMessage().contains("already exists"))) {
                    System.out.println("Oracle ensureCourierPacketExtraColumns: " + e.getMessage());
                }
            }
        }
    }

    private static void ensureCourierPacketExtraDirectionsTable(Connection c) throws Exception {
        if (!coreTableExists(c, "COURIER_PACKETS")) {
            return;
        }
        try (java.sql.Statement st = c.createStatement()) {
            st.execute("""
                    CREATE TABLE courier_packet_extra_directions (
                      packet_id NUMBER NOT NULL,
                      direction_id NUMBER NOT NULL,
                      CONSTRAINT pk_cped PRIMARY KEY (packet_id, direction_id),
                      CONSTRAINT fk_cped_p FOREIGN KEY (packet_id) REFERENCES courier_packets(id) ON DELETE CASCADE,
                      CONSTRAINT fk_cped_d FOREIGN KEY (direction_id) REFERENCES directions(id)
                    )
                    """);
        } catch (Exception e) {
            if (e.getMessage() == null
                    || (!e.getMessage().contains("ORA-00955") && !e.getMessage().contains("already"))) {
                System.out.println("Oracle ensureCourierPacketExtraDirectionsTable: " + e.getMessage());
            }
        }
        try (java.sql.Statement st = c.createStatement()) {
            st.execute("CREATE INDEX idx_cped_dir ON courier_packet_extra_directions (direction_id)");
        } catch (Exception e) {
            if (e.getMessage() == null || !e.getMessage().contains("ORA-00955")) {
                System.out.println("Oracle idx_cped_dir: " + e.getMessage());
            }
        }
    }

    private static void ensureMyShiftTables(Connection c) throws Exception {
        if (coreTableExists(c, "MYSHIFT_SIGNINS")) {
            return;
        }
        String[] ddl = {
                """
                CREATE TABLE myshift_signins (
                  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  user_id NUMBER NOT NULL,
                  signin_day VARCHAR2(10) NOT NULL,
                  sign_in_time VARCHAR2(32) NOT NULL,
                  sign_out_time VARCHAR2(32),
                  latitude NUMBER,
                  longitude NUMBER,
                  location_text VARCHAR2(4000),
                  country_code VARCHAR2(8),
                  city VARCHAR2(256),
                  ip_address VARCHAR2(64),
                  face_verified NUMBER(1) NOT NULL,
                  face_confidence NUMBER,
                  face_method VARCHAR2(64),
                  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                  CONSTRAINT fk_ms_user FOREIGN KEY (user_id) REFERENCES users(id)
                )
                """,
                "CREATE INDEX idx_myshift_user_day ON myshift_signins (user_id, signin_day)",
                "CREATE INDEX idx_myshift_signin_day ON myshift_signins (signin_day)"
        };
        try (java.sql.Statement st = c.createStatement()) {
            for (String sql : ddl) {
                st.execute(sql);
            }
        }
        System.out.println("Oracle: created myshift_signins table.");
    }

    private static void ensureMyShiftPlannedTable(Connection c) throws Exception {
        if (coreTableExists(c, "MYSHIFT_PLANNED")) {
            return;
        }
        String[] ddl = {
                """
                CREATE TABLE myshift_planned (
                  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  user_id NUMBER NOT NULL,
                  work_date VARCHAR2(10) NOT NULL,
                  shift_code VARCHAR2(32) NOT NULL,
                  created_by NUMBER,
                  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                  CONSTRAINT uq_mspl_user_day UNIQUE (user_id, work_date),
                  CONSTRAINT fk_mspl_user FOREIGN KEY (user_id) REFERENCES users (id)
                )
                """,
                "CREATE INDEX idx_mspl_user_date ON myshift_planned (user_id, work_date)"
        };
        try (java.sql.Statement st = c.createStatement()) {
            for (String sql : ddl) {
                st.execute(sql);
            }
        }
        System.out.println("Oracle: created myshift_planned table.");
    }

    private static void ensureUserAbsencesTable(Connection c) throws Exception {
        if (coreTableExists(c, "USER_ABSENCES")) {
            return;
        }
        String[] ddl = {
                """
                CREATE TABLE user_absences (
                  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  user_id NUMBER NOT NULL,
                  start_date VARCHAR2(32) NOT NULL,
                  end_date VARCHAR2(32) NOT NULL,
                  absence_type VARCHAR2(32) NOT NULL,
                  notes VARCHAR2(4000),
                  created_by NUMBER,
                  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                  CONSTRAINT fk_abs_user FOREIGN KEY (user_id) REFERENCES users(id),
                  CONSTRAINT fk_abs_creator FOREIGN KEY (created_by) REFERENCES users(id)
                )
                """,
                "CREATE INDEX idx_user_absences_user ON user_absences (user_id)",
                "CREATE INDEX idx_user_absences_dates ON user_absences (start_date, end_date)"
        };
        try (java.sql.Statement st = c.createStatement()) {
            for (String s : ddl) {
                st.execute(s);
            }
        }
        System.out.println("Oracle: created user_absences table.");
    }

    private static void ensureUserAbsencesMissionIdColumn(Connection c) throws Exception {
        if (!coreTableExists(c, "USER_ABSENCES") || oracleColumnExists(c, "USER_ABSENCES", "MISSION_ID")) {
            return;
        }
        try (java.sql.Statement st = c.createStatement()) {
            st.execute("ALTER TABLE user_absences ADD (mission_id NUMBER)");
        }
        System.out.println("Oracle: added user_absences.mission_id column.");
    }

    private static boolean oracleColumnExists(Connection c, String tableUpper, String columnUpper) throws Exception {
        try (PreparedStatement ps = c.prepareStatement(
                "SELECT 1 FROM user_tab_cols WHERE table_name = ? AND column_name = ?")) {
            ps.setString(1, tableUpper);
            ps.setString(2, columnUpper);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next();
            }
        }
    }

    /** Adds description CLOB when upgrading Oracle field_missions created before this column existed. */
    private static void ensureFieldMissionDescriptionColumn(Connection c) throws Exception {
        if (!coreTableExists(c, "FIELD_MISSIONS")
                || oracleColumnExists(c, "FIELD_MISSIONS", "DESCRIPTION")) {
            return;
        }
        try (java.sql.Statement st = c.createStatement()) {
            st.execute("ALTER TABLE field_missions ADD (description CLOB)");
        }
        System.out.println("Oracle: added field_missions.description column.");
    }

    /** Adds official mission order columns when upgrading Oracle field_missions. */
    private static void ensureFieldMissionOrderColumns(Connection c) throws Exception {
        if (!coreTableExists(c, "FIELD_MISSIONS")
                || oracleColumnExists(c, "FIELD_MISSIONS", "ORDER_REFERENCE")) {
            return;
        }
        try (java.sql.Statement st = c.createStatement()) {
            st.execute("""
                    ALTER TABLE field_missions ADD (
                      order_reference VARCHAR2(4000),
                      order_issue_date VARCHAR2(32),
                      order_issued_by VARCHAR2(4000),
                      order_body CLOB
                    )
                    """);
        }
        System.out.println("Oracle: added field_missions order columns.");
    }

    /** Adds field mission tables when upgrading an Oracle DB that predates this feature. */
    private static void ensureFieldMissionsTables(Connection c) throws Exception {
        if (coreTableExists(c, "FIELD_MISSIONS")) {
            return;
        }
        String[] ddl = {
                """
                CREATE TABLE field_missions (
                  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  mission_code VARCHAR2(64) NOT NULL,
                  title VARCHAR2(4000) NOT NULL,
                  site_location VARCHAR2(4000),
                  start_date VARCHAR2(32),
                  end_date VARCHAR2(32),
                  description CLOB,
                  objectives CLOB,
                  status VARCHAR2(32) DEFAULT 'PLANNED' NOT NULL,
                  report_text CLOB,
                  report_submitted_at TIMESTAMP,
                  report_author_id NUMBER,
                  lead_user_id NUMBER,
                  created_by NUMBER NOT NULL,
                  order_reference VARCHAR2(4000),
                  order_issue_date VARCHAR2(32),
                  order_issued_by VARCHAR2(4000),
                  order_body CLOB,
                  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                  CONSTRAINT uq_field_missions_code UNIQUE (mission_code),
                  CONSTRAINT fk_fm_lead FOREIGN KEY (lead_user_id) REFERENCES users(id),
                  CONSTRAINT fk_fm_creator FOREIGN KEY (created_by) REFERENCES users(id),
                  CONSTRAINT fk_fm_report_author FOREIGN KEY (report_author_id) REFERENCES users(id)
                )
                """,
                """
                CREATE TABLE field_mission_participants (
                  mission_id NUMBER NOT NULL,
                  user_id NUMBER NOT NULL,
                  CONSTRAINT pk_field_mission_participants PRIMARY KEY (mission_id, user_id),
                  CONSTRAINT fk_fmp_mission FOREIGN KEY (mission_id) REFERENCES field_missions(id) ON DELETE CASCADE,
                  CONSTRAINT fk_fmp_user FOREIGN KEY (user_id) REFERENCES users(id)
                )
                """,
                """
                CREATE TABLE field_mission_attachments (
                  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  mission_id NUMBER NOT NULL,
                  file_name VARCHAR2(4000) NOT NULL,
                  file_path VARCHAR2(4000) NOT NULL,
                  uploaded_by NUMBER,
                  uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                  CONSTRAINT fk_fma_mission FOREIGN KEY (mission_id) REFERENCES field_missions(id) ON DELETE CASCADE,
                  CONSTRAINT fk_fma_user FOREIGN KEY (uploaded_by) REFERENCES users(id)
                )
                """
        };
        try (java.sql.Statement st = c.createStatement()) {
            for (String sql : ddl) {
                st.execute(sql);
            }
        }
        System.out.println("Oracle: created field_missions / participants / attachments tables.");
    }

    private static void ensureFieldMissionOrderAttachmentsTable(Connection c) throws Exception {
        if (coreTableExists(c, "FIELD_MISSION_ORDER_ATTACHMENTS") || !coreTableExists(c, "FIELD_MISSIONS")) {
            return;
        }
        try (java.sql.Statement st = c.createStatement()) {
            st.execute("""
                    CREATE TABLE field_mission_order_attachments (
                      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      mission_id NUMBER NOT NULL,
                      file_name VARCHAR2(4000) NOT NULL,
                      file_path VARCHAR2(4000) NOT NULL,
                      uploaded_by NUMBER,
                      uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                      CONSTRAINT fk_fmoa_mission FOREIGN KEY (mission_id) REFERENCES field_missions(id) ON DELETE CASCADE,
                      CONSTRAINT fk_fmoa_user FOREIGN KEY (uploaded_by) REFERENCES users(id)
                    )
                    """);
        }
        System.out.println("Oracle: created field_mission_order_attachments table.");
    }

    private static void ensureFieldMissionDetailAttachmentsTable(Connection c) throws Exception {
        if (coreTableExists(c, "FIELD_MISSION_DETAIL_ATTACHMENTS") || !coreTableExists(c, "FIELD_MISSIONS")) {
            return;
        }
        try (java.sql.Statement st = c.createStatement()) {
            st.execute("""
                    CREATE TABLE field_mission_detail_attachments (
                      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      mission_id NUMBER NOT NULL,
                      file_name VARCHAR2(4000) NOT NULL,
                      file_path VARCHAR2(4000) NOT NULL,
                      uploaded_by NUMBER,
                      uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                      CONSTRAINT fk_fmda_mission FOREIGN KEY (mission_id) REFERENCES field_missions(id) ON DELETE CASCADE,
                      CONSTRAINT fk_fmda_user FOREIGN KEY (uploaded_by) REFERENCES users(id)
                    )
                    """);
        }
        System.out.println("Oracle: created field_mission_detail_attachments table.");
    }

    private static void ensureFieldMissionReportAuthorColumn(Connection c) throws Exception {
        if (!coreTableExists(c, "FIELD_MISSIONS")
                || oracleColumnExists(c, "FIELD_MISSIONS", "REPORT_AUTHOR_ID")) {
            return;
        }
        try (java.sql.Statement st = c.createStatement()) {
            st.execute("""
                    ALTER TABLE field_missions ADD (
                      report_author_id NUMBER,
                      CONSTRAINT fk_fm_report_author_mig FOREIGN KEY (report_author_id) REFERENCES users(id)
                    )
                    """);
            st.execute("""
                    UPDATE field_missions SET report_author_id = created_by
                    WHERE report_author_id IS NULL AND report_text IS NOT NULL
                    """);
        }
        System.out.println("Oracle: added field_missions.report_author_id column.");
    }

    private static boolean coreTableExists(Connection c, String tableName) throws Exception {
        try (PreparedStatement ps = c.prepareStatement(
                "SELECT 1 FROM user_tables WHERE table_name = ?")) {
            ps.setString(1, tableName.toUpperCase());
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next();
            }
        }
    }

    private static void mergeSousDirection(Connection c, String name) throws Exception {
        String sql = """
            MERGE INTO sous_directions t
            USING (SELECT ? AS name FROM dual) s
            ON (t.name = s.name)
            WHEN NOT MATCHED THEN INSERT (name) VALUES (s.name)
            """;
        try (PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setString(1, name);
            ps.executeUpdate();
        }
    }

    private static void seedCoreData(Connection c) throws Exception {
        for (String n : new String[] { "AUTRE" }) {
            mergeSousDirection(c, n);
        }

        int autreId;
        try (PreparedStatement q = c.prepareStatement("SELECT id FROM sous_directions WHERE name = 'AUTRE'")) {
            ResultSet rs = q.executeQuery();
            if (!rs.next()) {
                throw new IllegalStateException("AUTRE sous_direction missing");
            }
            autreId = rs.getInt(1);
        }

        String[] directionNames = {
                "Bureau de Coordination",
                "Direction des Ressources Humaines",
                "Direction de la Réglementation et de la Facilitation",
                "Direction de la Lutte contre la Fraude",
                "Direction du Tarif et des Règles d’Origine",
                "Direction des Affaires Juridiques et Contentieuses",
                "Direction de la Valeur",
                "Direction des Huiles Minérales",
                "Direction des Autres Produits d’Accises",
                "Direction des Recettes du Trésor",
                "Direction des Finances Internes",
                "Direction des Équipements et Logistique",
                "Direction des Statistiques, Documentation et Études Économiques",
                com.app.dao.DirectionDAO.CANONICAL_DIRECTION_SYSTEMES_TI,
                "Direction de l’Audit Interne",
                "Direction des Réformes et de la Modernisation"
        };
        String mergeDir = """
            MERGE INTO directions t
            USING (SELECT ? AS name, ? AS sous_direction_id FROM dual) s
            ON (t.name = s.name)
            WHEN NOT MATCHED THEN INSERT (name, sous_direction_id) VALUES (s.name, s.sous_direction_id)
            """;
        try (PreparedStatement ps = c.prepareStatement(mergeDir)) {
            for (String name : directionNames) {
                ps.setString(1, name);
                ps.setInt(2, autreId);
                ps.executeUpdate();
            }
        }

        String mergeDept = """
            MERGE INTO departments t
            USING (SELECT ? AS name FROM dual) s
            ON (t.name = s.name)
            WHEN NOT MATCHED THEN INSERT (name) VALUES (s.name)
            """;
        String[] deptNames = {
                "Bureau de Coordination",
                "Direction des Ressources Humaines",
                "Direction de Réglementation et Facilitation",
                "Direction de la Lutte contre la Fraude",
                "Direction du Tarif et Règles d’origine",
                "Direction des Affaires Juridiques et Contentieuses",
                "Direction de la Valeur",
                "Direction des Huiles Minérales",
                "Direction des Autres Produits d’Accises",
                "Direction des Recettes du Trésor",
                "Direction des Finances Internes",
                "Direction des Equipements et Logistique",
                "Direction des statistiques, Documentation et Etudes Economiques",
                com.app.dao.DirectionDAO.CANONICAL_DIRECTION_SYSTEMES_TI,
                "Direction de l’Audit Interne",
                "Direction de Réformes et Modernisation"
        };
        try (PreparedStatement ps = c.prepareStatement(mergeDept)) {
            for (String name : deptNames) {
                ps.setString(1, name);
                ps.executeUpdate();
            }
        }

        try (PreparedStatement up = c.prepareStatement(
                "UPDATE departments SET escalation_level1 = NULL WHERE escalation_level1 = 0")) {
            up.executeUpdate();
        }
        try (PreparedStatement up = c.prepareStatement(
                "UPDATE departments SET escalation_level2 = NULL WHERE escalation_level2 = 0")) {
            up.executeUpdate();
        }

        String[][] defaultAdmins = {
                {"admin", "admin123"},
                {"admin2", "admin123"},
                {"admin3", "admin123"}
        };
        for (String[] adminData : defaultAdmins) {
            String username = adminData[0];
            String password = adminData[1];
            try (PreparedStatement check = c.prepareStatement("SELECT id FROM users WHERE username = ?")) {
                check.setString(1, username);
                ResultSet rsAdmin = check.executeQuery();
                if (!rsAdmin.next()) {
                    try (PreparedStatement ps = c.prepareStatement("""
                            INSERT INTO users(username, password_hash, role, active, failed_attempts, must_change_password)
                            VALUES (?, ?, 'ADMIN', 1, 0, 0)
                            """)) {
                        ps.setString(1, username);
                        ps.setString(2, BCrypt.hashpw(password, BCrypt.gensalt()));
                        ps.executeUpdate();
                    }
                    System.out.println("Oracle: created default admin: " + username);
                } else {
                    try (PreparedStatement update = c.prepareStatement("""
                            UPDATE users SET password_hash = ?, active = 1, failed_attempts = 0 WHERE username = ?
                            """)) {
                        update.setString(1, BCrypt.hashpw(password, BCrypt.gensalt()));
                        update.setString(2, username);
                        update.executeUpdate();
                    }
                    System.out.println("Oracle: reset admin password: " + username);
                }
            }
        }
    }
}
