-- SYSCO / Oracle 21c+ bootstrap (run once; use dedicated schema user)

CREATE TABLE sous_directions (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(255) NOT NULL,
  CONSTRAINT uq_sous_directions_name UNIQUE (name)
);

CREATE TABLE directions (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(512) NOT NULL,
  sous_direction_id NUMBER,
  CONSTRAINT uq_directions_name UNIQUE (name),
  CONSTRAINT fk_directions_sous FOREIGN KEY (sous_direction_id) REFERENCES sous_directions(id)
);

CREATE TABLE direction_sous_direction_map (
  direction_id NUMBER NOT NULL,
  sous_direction_id NUMBER NOT NULL,
  CONSTRAINT pk_dir_sous_map PRIMARY KEY (direction_id, sous_direction_id),
  CONSTRAINT fk_dsm_dir FOREIGN KEY (direction_id) REFERENCES directions(id) ON DELETE CASCADE,
  CONSTRAINT fk_dsm_sous FOREIGN KEY (sous_direction_id) REFERENCES sous_directions(id) ON DELETE CASCADE
);

CREATE TABLE departments (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(512) NOT NULL,
  escalation_level1 NUMBER,
  escalation_level2 NUMBER,
  CONSTRAINT uq_departments_name UNIQUE (name)
);

CREATE TABLE users (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR2(255) NOT NULL,
  matricule VARCHAR2(255),
  password_hash VARCHAR2(255),
  role VARCHAR2(64) NOT NULL,
  active NUMBER(1) DEFAULT 1,
  sous_direction_id NUMBER,
  direction_id NUMBER,
  hidden NUMBER(1) DEFAULT 0,
  must_change_password NUMBER(1) DEFAULT 1,
  failed_attempts NUMBER DEFAULT 0,
  lock_until TIMESTAMP,
  email VARCHAR2(512),
  attendance_signature VARCHAR2(64),
  CONSTRAINT uq_users_username UNIQUE (username),
  CONSTRAINT fk_users_sous FOREIGN KEY (sous_direction_id) REFERENCES sous_directions(id),
  CONSTRAINT fk_users_dir FOREIGN KEY (direction_id) REFERENCES directions(id)
);

CREATE TABLE user_permissions (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER,
  permission VARCHAR2(255),
  CONSTRAINT fk_user_perm_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE user_absences (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  start_date VARCHAR2(32) NOT NULL,
  end_date VARCHAR2(32) NOT NULL,
  absence_type VARCHAR2(32) NOT NULL,
  notes VARCHAR2(4000),
  created_by NUMBER,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_abs_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_abs_creator FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE INDEX idx_user_absences_user ON user_absences (user_id);
CREATE INDEX idx_user_absences_dates ON user_absences (start_date, end_date);

CREATE TABLE tickets (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR2(4000),
  description CLOB,
  priority VARCHAR2(64),
  status VARCHAR2(64),
  ticket_type VARCHAR2(32) NOT NULL,
  department_id NUMBER,
  assigned_to NUMBER,
  created_by NUMBER,
  updated_by NUMBER,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  started_at TIMESTAMP,
  closed_at TIMESTAMP,
  resolution_minutes NUMBER,
  sla_hours NUMBER DEFAULT 24,
  merged_into NUMBER,
  merge_note VARCHAR2(4000),
  ticket_number VARCHAR2(128),
  sla_breached NUMBER(1) DEFAULT 0,
  CONSTRAINT fk_tickets_dept FOREIGN KEY (department_id) REFERENCES departments(id),
  CONSTRAINT fk_tickets_assign FOREIGN KEY (assigned_to) REFERENCES users(id),
  CONSTRAINT fk_tickets_creator FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_tickets_updater FOREIGN KEY (updated_by) REFERENCES users(id)
);

CREATE TABLE ticket_assignments (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id NUMBER NOT NULL,
  agent_id NUMBER NOT NULL,
  assigned_to NUMBER,
  assigned_by NUMBER,
  assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR2(64) DEFAULT 'ASSIGNED',
  started_at TIMESTAMP,
  closed_at TIMESTAMP,
  duration_minutes NUMBER,
  active NUMBER(1) DEFAULT 1,
  from_role VARCHAR2(64),
  to_role VARCHAR2(64),
  assignment_type VARCHAR2(64) DEFAULT 'SINGLE',
  CONSTRAINT fk_ta_ticket FOREIGN KEY (ticket_id) REFERENCES tickets(id),
  CONSTRAINT fk_ta_agent FOREIGN KEY (agent_id) REFERENCES users(id),
  CONSTRAINT fk_ta_assigner FOREIGN KEY (assigned_by) REFERENCES users(id)
);

CREATE TABLE ticket_tasks (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id NUMBER NOT NULL,
  parent_assignment_id NUMBER,
  parent_task_id NUMBER,
  title VARCHAR2(4000) NOT NULL,
  description CLOB,
  assigned_to NUMBER NOT NULL,
  assigned_by NUMBER NOT NULL,
  status VARCHAR2(64) DEFAULT 'PENDING' NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  started_at TIMESTAMP,
  completed_at TIMESTAMP,
  closed_at TIMESTAMP,
  due_date VARCHAR2(64),
  resolution_minutes NUMBER,
  duration_minutes NUMBER,
  attachment_path VARCHAR2(4000),
  created_by NUMBER,
  priority VARCHAR2(64),
  CONSTRAINT fk_tt_ticket FOREIGN KEY (ticket_id) REFERENCES tickets(id),
  CONSTRAINT fk_tt_passign FOREIGN KEY (parent_assignment_id) REFERENCES ticket_assignments(id),
  CONSTRAINT fk_tt_assignee FOREIGN KEY (assigned_to) REFERENCES users(id),
  CONSTRAINT fk_tt_assigner FOREIGN KEY (assigned_by) REFERENCES users(id),
  CONSTRAINT fk_tt_creator FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE task_events (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id NUMBER NOT NULL,
  user_id NUMBER,
  event_type VARCHAR2(128),
  description CLOB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_te_task FOREIGN KEY (task_id) REFERENCES ticket_tasks(id),
  CONSTRAINT fk_te_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE task_assignments (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id NUMBER,
  user_id NUMBER
);

CREATE TABLE ticket_attachments (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id NUMBER NOT NULL,
  file_name VARCHAR2(1024),
  file_path VARCHAR2(4000),
  file_type VARCHAR2(256),
  uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  uploaded_by NUMBER,
  CONSTRAINT fk_tatt_ticket FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE CASCADE,
  CONSTRAINT fk_tatt_user FOREIGN KEY (uploaded_by) REFERENCES users(id)
);

CREATE TABLE system_audit (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR2(255),
  action VARCHAR2(255) NOT NULL,
  entity VARCHAR2(255),
  entity_id NUMBER,
  details CLOB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE task_comments (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id NUMBER NOT NULL,
  user_id NUMBER NOT NULL,
  "comment" CLOB NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_tc_task FOREIGN KEY (task_id) REFERENCES ticket_tasks(id),
  CONSTRAINT fk_tc_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE task_attachments (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id NUMBER NOT NULL,
  file_name VARCHAR2(1024),
  file_path VARCHAR2(4000),
  file_type VARCHAR2(256),
  uploaded_by NUMBER,
  uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_tat_task FOREIGN KEY (task_id) REFERENCES ticket_tasks(id),
  CONSTRAINT fk_tat_user FOREIGN KEY (uploaded_by) REFERENCES users(id)
);

CREATE TABLE ticket_escalations (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id NUMBER NOT NULL,
  escalated_by NUMBER NOT NULL,
  escalated_from NUMBER,
  escalated_to NUMBER NOT NULL,
  reason CLOB,
  escalated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_te_ticket FOREIGN KEY (ticket_id) REFERENCES tickets(id),
  CONSTRAINT fk_te_by FOREIGN KEY (escalated_by) REFERENCES users(id),
  CONSTRAINT fk_te_from FOREIGN KEY (escalated_from) REFERENCES users(id),
  CONSTRAINT fk_te_to FOREIGN KEY (escalated_to) REFERENCES users(id)
);

CREATE TABLE ticket_events (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id NUMBER NOT NULL,
  user_id NUMBER,
  event_type VARCHAR2(128),
  "comment" CLOB,
  description CLOB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_tev_ticket FOREIGN KEY (ticket_id) REFERENCES tickets(id),
  CONSTRAINT fk_tev_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE messages (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id NUMBER,
  receiver_id NUMBER,
  "message" CLOB,
  is_read NUMBER(1) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_msg_sender FOREIGN KEY (sender_id) REFERENCES users(id),
  CONSTRAINT fk_msg_recv FOREIGN KEY (receiver_id) REFERENCES users(id)
);

CREATE TABLE ticket_comments (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id NUMBER NOT NULL,
  user_id NUMBER NOT NULL,
  "comment" CLOB NOT NULL,
  image_path VARCHAR2(4000),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_tcom_ticket FOREIGN KEY (ticket_id) REFERENCES tickets(id),
  CONSTRAINT fk_tcom_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE notifications (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  title VARCHAR2(512) NOT NULL,
  "message" CLOB NOT NULL,
  type VARCHAR2(128),
  target_type VARCHAR2(128),
  target_id NUMBER,
  target_ref VARCHAR2(512),
  is_read NUMBER(1) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_notif_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE datashare_files (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_name VARCHAR2(1024),
  file_path VARCHAR2(4000),
  shared_by_id NUMBER,
  shared_by_name VARCHAR2(255),
  shared_role VARCHAR2(128),
  sous_direction VARCHAR2(255),
  date_shared VARCHAR2(64),
  time_shared VARCHAR2(64),
  expiration_date VARCHAR2(64),
  file_size NUMBER DEFAULT 0,
  downloads NUMBER DEFAULT 0
);

CREATE TABLE datashare_recipients (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_id NUMBER,
  recipient_id NUMBER,
  recipient_name VARCHAR2(255),
  recipient_role VARCHAR2(128),
  otp_hash VARCHAR2(512),
  otp_expires_at VARCHAR2(64),
  otp_verified_at VARCHAR2(64)
);

CREATE TABLE datashare_audit (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_id NUMBER,
  file_name VARCHAR2(1024),
  shared_by_id NUMBER,
  shared_by_name VARCHAR2(255),
  recipient_id NUMBER,
  recipient_name VARCHAR2(255),
  action VARCHAR2(128),
  "date" VARCHAR2(64),
  "time" VARCHAR2(64)
);

CREATE TABLE datashare_messages (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_id NUMBER,
  sender_id NUMBER,
  sender_name VARCHAR2(255),
  message CLOB,
  date_sent VARCHAR2(64),
  time_sent VARCHAR2(64)
);

CREATE TABLE ticket_history (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id NUMBER,
  action VARCHAR2(255),
  description CLOB,
  user_id NUMBER,
  username VARCHAR2(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ticket_close_requests (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id NUMBER NOT NULL,
  requested_by NUMBER NOT NULL,
  requested_to NUMBER NOT NULL,
  reason CLOB,
  status VARCHAR2(64) DEFAULT 'PENDING',
  requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  decided_by NUMBER,
  decided_at TIMESTAMP,
  decision_note CLOB,
  CONSTRAINT fk_tcr_ticket FOREIGN KEY (ticket_id) REFERENCES tickets(id),
  CONSTRAINT fk_tcr_req FOREIGN KEY (requested_by) REFERENCES users(id),
  CONSTRAINT fk_tcr_to FOREIGN KEY (requested_to) REFERENCES users(id),
  CONSTRAINT fk_tcr_dec FOREIGN KEY (decided_by) REFERENCES users(id)
);

CREATE TABLE ticket_external_escalations (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id NUMBER NOT NULL,
  from_direction_id NUMBER,
  to_direction_id NUMBER NOT NULL,
  to_sous_direction_id NUMBER NOT NULL,
  escalated_by NUMBER NOT NULL,
  status VARCHAR2(64) DEFAULT 'PENDING',
  note CLOB,
  requested_approver_id NUMBER,
  approved_by NUMBER,
  approved_at TIMESTAMP,
  assigned_to NUMBER,
  assigned_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_tee_ticket FOREIGN KEY (ticket_id) REFERENCES tickets(id),
  CONSTRAINT fk_tee_fd FOREIGN KEY (from_direction_id) REFERENCES directions(id),
  CONSTRAINT fk_tee_td FOREIGN KEY (to_direction_id) REFERENCES directions(id),
  CONSTRAINT fk_tee_ts FOREIGN KEY (to_sous_direction_id) REFERENCES sous_directions(id),
  CONSTRAINT fk_tee_by FOREIGN KEY (escalated_by) REFERENCES users(id),
  CONSTRAINT fk_tee_ra FOREIGN KEY (requested_approver_id) REFERENCES users(id),
  CONSTRAINT fk_tee_ab FOREIGN KEY (approved_by) REFERENCES users(id),
  CONSTRAINT fk_tee_asg FOREIGN KEY (assigned_to) REFERENCES users(id)
);

CREATE TABLE automated_jobs (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_title VARCHAR2(512) NOT NULL,
  job_description CLOB,
  due_at VARCHAR2(64) NOT NULL,
  reminder_minutes NUMBER DEFAULT 60,
  assignee_user_id NUMBER,
  created_by NUMBER,
  recurrence VARCHAR2(32) DEFAULT 'ONCE',
  active NUMBER(1) DEFAULT 1,
  last_reminder_at VARCHAR2(64),
  last_ticket_created_at VARCHAR2(64),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_aj_assignee FOREIGN KEY (assignee_user_id) REFERENCES users(id),
  CONSTRAINT fk_aj_creator FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE monthly_reports (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  month_key VARCHAR2(32) NOT NULL,
  generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  file_path VARCHAR2(4000),
  total_tickets NUMBER DEFAULT 0,
  open_tickets NUMBER DEFAULT 0,
  in_progress_tickets NUMBER DEFAULT 0,
  closed_tickets NUMBER DEFAULT 0,
  CONSTRAINT uq_monthly_reports_key UNIQUE (month_key)
);

CREATE TABLE field_missions (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mission_code VARCHAR2(64) NOT NULL,
  title VARCHAR2(4000) NOT NULL,
  site_location VARCHAR2(4000),
  start_date VARCHAR2(32),
  end_date VARCHAR2(32),
  description CLOB,
  objectives CLOB,
  status VARCHAR2(32) DEFAULT 'PLANNED' NOT NULL,
  report_text CLOB,
  report_submitted_at TIMESTAMP,
  report_author_id NUMBER,
  lead_user_id NUMBER,
  created_by NUMBER NOT NULL,
  order_reference VARCHAR2(4000),
  order_issue_date VARCHAR2(32),
  order_issued_by VARCHAR2(4000),
  order_body CLOB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_field_missions_code UNIQUE (mission_code),
  CONSTRAINT fk_fm_lead FOREIGN KEY (lead_user_id) REFERENCES users(id),
  CONSTRAINT fk_fm_creator FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_fm_report_author FOREIGN KEY (report_author_id) REFERENCES users(id)
);

CREATE TABLE field_mission_participants (
  mission_id NUMBER NOT NULL,
  user_id NUMBER NOT NULL,
  CONSTRAINT pk_field_mission_participants PRIMARY KEY (mission_id, user_id),
  CONSTRAINT fk_fmp_mission FOREIGN KEY (mission_id) REFERENCES field_missions(id) ON DELETE CASCADE,
  CONSTRAINT fk_fmp_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE field_mission_attachments (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mission_id NUMBER NOT NULL,
  file_name VARCHAR2(4000) NOT NULL,
  file_path VARCHAR2(4000) NOT NULL,
  uploaded_by NUMBER,
  uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_fma_mission FOREIGN KEY (mission_id) REFERENCES field_missions(id) ON DELETE CASCADE,
  CONSTRAINT fk_fma_user FOREIGN KEY (uploaded_by) REFERENCES users(id)
);

CREATE UNIQUE INDEX idx_users_matricule ON users (
  (CASE WHEN matricule IS NOT NULL AND LENGTH(TRIM(matricule)) > 0 THEN matricule END)
);

CREATE UNIQUE INDEX idx_single_active_assignment ON ticket_assignments (
  (CASE WHEN active = 1 AND assignment_type = 'SINGLE' THEN ticket_id END)
);

CREATE INDEX idx_ticket_assignment_lookup ON ticket_assignments(ticket_id, active);
CREATE INDEX idx_task_assigned ON ticket_tasks(assigned_to);
CREATE INDEX idx_task_ticket ON ticket_tasks(ticket_id);
CREATE INDEX idx_task_status ON ticket_tasks(status);
CREATE INDEX idx_ticket_assignment ON ticket_assignments(ticket_id, assigned_to);
CREATE INDEX idx_ticket_status ON tickets(status);
CREATE INDEX idx_ticket_department ON tickets(department_id);
CREATE INDEX idx_ticket_created ON tickets(created_at);
CREATE INDEX idx_messages_users ON messages(sender_id, receiver_id);
CREATE INDEX idx_ticket_assigned_t ON tickets(assigned_to);
